name: ECSS Backend Django - Production Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.13'
  AZURE_WEBAPP_NAME: 'ecss-backend-django'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout
      id-token: write  # Required for Azure login

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          
          if [ -f djangoPython/requirements.txt ]; then
            echo "Installing dependencies from djangoPython/requirements.txt"
            pip install -r djangoPython/requirements.txt --no-cache-dir
            echo "✓ Dependencies installed successfully"
          else
            echo "❌ requirements.txt not found in djangoPython/ directory"
            exit 1
          fi

      - name: Run Django checks
        run: |
          source venv/bin/activate
          cd djangoPython
          python manage.py check --deploy
        continue-on-error: true

      - name: Collect static files
        run: |
          source venv/bin/activate
          cd djangoPython
          python manage.py collectstatic --noinput --clear
        continue-on-error: true

      - name: Create deployment package
        run: |
          source venv/bin/activate
          rm -rf deployment_package
          mkdir -p deployment_package
          cp -r djangoPython/* deployment_package/
          mkdir -p deployment_package/.python_packages/lib/python${{ env.PYTHON_VERSION }}/site-packages
          echo "Copying Python packages..."
          cp -r venv/lib/python*/site-packages/* deployment_package/.python_packages/lib/python${{ env.PYTHON_VERSION }}/site-packages/ 2>/dev/null || echo "Package copy completed"
          
          # Test WSGI module before deployment
          echo "=== Testing WSGI module ==="
          cd djangoPython
          python -c "import djangoPython.wsgi; print('✓ WSGI module imports successfully')" || echo "❌ WSGI module import failed"
          cd ..
          
          # Create startup command that matches the directory structure
          cat > deployment_package/startup.txt << 'EOF'
          #!/bin/bash
          cd /home/site/wwwroot
          export PYTHONPATH="/home/site/wwwroot:/home/site/wwwroot/.python_packages/lib/python3.13/site-packages:$PYTHONPATH"
          export DJANGO_SETTINGS_MODULE=djangoPython.settings
          export PYTHONUNBUFFERED=1
          export PORT=${PORT:-8000}
          echo "Starting Django application..."
          echo "Current directory: $(pwd)"
          echo "WSGI module: djangoPython.wsgi:application"
          gunicorn --bind=0.0.0.0:$PORT --timeout=600 --workers=4 djangoPython.wsgi:application
          EOF
          
          find deployment_package -name "*.pyc" -delete 2>/dev/null || true
          find deployment_package -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
          find deployment_package -name ".DS_Store" -delete 2>/dev/null || true
          find deployment_package -name "*.pyo" -delete 2>/dev/null || true
          find deployment_package -name "tests" -type d -exec rm -rf {} + 2>/dev/null || true
          
          # Debug: Show deployment package structure
          echo "=== Deployment Package Structure ==="
          ls -la deployment_package/
          echo "=== Django WSGI file check ==="
          if [ -f deployment_package/djangoPython/wsgi.py ]; then
            echo "✓ WSGI file found at deployment_package/djangoPython/wsgi.py"
          else
            echo "❌ WSGI file NOT found - checking structure..."
            find deployment_package -name "wsgi.py" -type f
          fi
          
          cd deployment_package
          zip -r ../release.zip . -x "*.DS_Store*" "*.git*"
          cd ..
          
          echo "✓ Deployment package created successfully"
          echo "Package size: $(du -h release.zip | cut -f1)"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DB1EDA88A3DA4E8D846F3C3D5AB12A22 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22BDF8F60B124137A56F942213EAB1D3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1F917677349441DF9FFD4FFAA1773557 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          package: release.zip

      - name: Verify deployment
        run: |
          echo "Deployment completed successfully!"
          echo "Application URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
          sleep 30
          response=$(curl -s -o /dev/null -w "%{http_code}" "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net" || echo "000")
          if [ "$response" = "200" ] || [ "$response" = "302" ]; then
            echo "✓ Application is responding (HTTP $response)"
          else
            echo "⚠️ Application health check returned HTTP $response"
          fi
