name: Build and deploy Python app to Azure Web App - ecss-backend-django

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv /tmp/venv
          source /tmp/venv/bin/activate

      - name: Install dependencies
        run: |
          source /tmp/venv/bin/activate
          pip install --upgrade pip
          pip install -r djangoPython/requirements.txt

      # Optional: Add test steps here (pytest, Django tests, etc.)

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "*/tmp/venv/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F6493B6D4208411C837A9687049B1A56 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EB79F461F4B4430CAEDF712D5D8E3B10 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4129D336120440A3940229E354C62FAB }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ecss-backend-django'
          slot-name: 'Production'
          package: release.zip
