name: ECSS Backend Django - Production Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.13'
  AZURE_WEBAPP_NAME: 'ecss-backend-django'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r djangoPython/requirements.txt

      - name: Create deployment package
        run: |
          mkdir deployment_package
          cp -r djangoPython/* deployment_package/
          
          # Create startup script
          cat > deployment_package/startup.sh << 'EOF'
          #!/bin/bash
          export DJANGO_SETTINGS_MODULE=djangoPython.settings
          export PYTHONUNBUFFERED=1
          gunicorn --bind=0.0.0.0:$PORT --workers=2 djangoPython.wsgi:application
          EOF
          
          chmod +x deployment_package/startup.sh
          cd deployment_package && zip -r ../app.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DB1EDA88A3DA4E8D846F3C3D5AB12A22 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22BDF8F60B124137A56F942213EAB1D3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1F917677349441DF9FFD4FFAA1773557 }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.zip

      - name: Configure startup
        run: |
          az webapp config set \
            --resource-group ecss-backend-rg \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --startup-file "gunicorn --bind=0.0.0.0:\$PORT --workers=2 djangoPython.wsgi:application"
          
          az webapp config appsettings set \
            --resource-group ecss-backend-rg \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --settings \
            DJANGO_SETTINGS_MODULE=djangoPython.settings \
            SCM_DO_BUILD_DURING_DEPLOYMENT=false \
            ENABLE_ORYX_BUILD=false
