name: ECSS Backend Django - Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout
      id-token: write  # Required for Azure OIDC login

    environment:
      name: 'Production'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          cd djangoPython
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          cd djangoPython
          # Add your test commands here if you have tests
          # python manage.py test
          echo "Skipping tests for now"

      - name: Prepare Django application for deployment
        run: |
          cd djangoPython
          # Collect static files if needed
          # python manage.py collectstatic --noinput
          
          # Create deployment package
          ls -la
          echo "Django application prepared for deployment"

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38E8FE3E777C49248149EC6F5DFB03B7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8B779764C58E492CA30F9427C7F5E046 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3AD277132D54AFE83E323AED9C1A781 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecss-backend-django'
          slot-name: 'Production'
          package: './djangoPython'
          
      - name: Verify deployment
        run: |
          echo "Deployment completed successfully"
          # Optional: Add health check endpoint verification
          # curl -f https://ecss-backend-django.azurewebsites.net/health || exit 1
          