name: ECSS Backend Django

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout
      id-token: write  # Required for Azure login

    environment:
      name: 'Production'

    steps:
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        #if: steps.determine_deployment.outputs.deploy == 'true'

      - name: Install dependencies
        run: |
          sudo pip install --upgrade pip
          sudo pip install -r requirements.txt
        #if: steps.determine_deployment.outputs.deploy == 'true'

      - name: Zip artifact for deployment
        run: |

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DB1EDA88A3DA4E8D846F3C3D5AB12A22 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22BDF8F60B124137A56F942213EAB1D3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1F917677349441DF9FFD4FFAA1773557 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecss-backend-django'
          slot-name: 'Production'
          package: release.zip
