name: ECSS Backend Django

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout
      id-token: write  # Required for Azure login

    environment:
      name: 'Production'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the last 2 commits to compare

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "VIRTUAL_ENV=venv" >> $GITHUB_ENV
          echo "venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          # Check if requirements.txt exists in root or djangoPython directory
          if [ -f requirements.txt ]; then
            echo "Installing from root requirements.txt"
            pip install -r requirements.txt
          elif [ -f djangoPython/requirements.txt ]; then
            echo "Installing from djangoPython/requirements.txt"
            pip install -r djangoPython/requirements.txt
          else
            echo "No requirements.txt found. Creating basic Django requirements..."
            pip install Django djangorestframework django-cors-headers
          fi

      - name: Collect static files (if Django)
        run: |
          source venv/bin/activate
          cd djangoPython
          if [ -f manage.py ]; then
            python manage.py collectstatic --noinput || echo "Static files collection skipped"
          fi

      - name: Run Django tests (optional)
        run: |
          source venv/bin/activate
          cd djangoPython
          if [ -f manage.py ]; then
            python manage.py test --verbosity=2 || echo "Tests skipped or failed"
          fi
        continue-on-error: true

      - name: Zip artifact for deployment
        run: |
          # Create deployment package excluding unnecessary files
          zip -r release.zip djangoPython \
            -x "djangoPython/venv/*" \
            -x "djangoPython/__pycache__/*" \
            -x "djangoPython/*/__pycache__/*" \
            -x "djangoPython/*/*/__pycache__/*" \
            -x "djangoPython/.env" \
            -x "djangoPython/db.sqlite3" \
            -x "djangoPython/media/*" \
            -x "djangoPython/static/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DB1EDA88A3DA4E8D846F3C3D5AB12A22 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22BDF8F60B124137A56F942213EAB1D3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1F917677349441DF9FFD4FFAA1773557 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecss-backend-django'
          slot-name: 'Production'
          package: release.zip